name: ubuntu-r-base

on:
  push:
    branches:
      - main
    paths: # rebuild when ubuntu image is modified
      - "debian.Dockerfile"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository code
        uses: actions/checkout@v2

      - name: Cancel Previous Workflow
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set of image meta attributes
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.REGISTRY_USER }}/r-base
          # generate tags based on the following attributes
          tags: |
            ${{ secrets.GITHUB_SHA }}
            latest
            ubuntu
            ${{ secrets.R_VERSION }}-ubuntu

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Available QEMU platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Available buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: ${{ secrets.REGISTRY_URL }}

      - name: Build and push the docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./ubuntu.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/arm,linux/386
          tags: ${{ steps.meta.outputs.tags }}

      - name: Logout of docker registry
        run: docker logout
